### ISSUE TITLE
Sample does not work

### ISSUE THREAD

**Issue by jutlag** [avinor/terraform-azurerm-monitor-diagnostics#2]
Tried the sample and it doesn't work. Getting various errors indicating missing variables in the source. My code is very simple with hard coded values and I tried different combinations.

The sample is nt very helpful and has lack of documentation

**Comment by yngveh** [comment]
@jutlag Can you please attach the inputs you are using and the errors you getting ?

**Comment by yngveh** [comment]
@jutlag Are you using terraform direct or are you using our terraform tool "tau" as the example is made for?

"Example how to create diagnostic settings for a subscription, deployed using tau."

**Comment by jutlag** [comment]
No longer needed
